# Generated by Django 2.0.2 on 2018-02-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=80)),
                ('name_zh', models.CharField(max_length=80, verbose_name='Name (Chinese)')),
                ('desc', models.CharField(max_length=255, verbose_name='Description')),
                ('desc_zh', models.CharField(max_length=255, verbose_name='Description (Chinese)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
