# Generated by Django 2.0.2 on 2018-02-26 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('iso639_3', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ISO 639-3 Code')),
                ('name', models.CharField(max_length=255)),
                ('name_zh', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_zh', models.CharField(blank=True, max_length=255, verbose_name='Name (Chinese)')),
                ('address', models.TextField()),
                ('address_zh', models.TextField(blank=True, verbose_name='Address (Chinese)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('fax', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('lawsochk_profile', models.URLField(blank=True, null=True, verbose_name='hklawsoc.org.hk Profile URL')),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('X', 'Invalid'), ('T', 'Free Trial'), (' ', 'Normal'), ('!', 'Not Paying')], default=' ', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_zh', models.CharField(blank=True, max_length=255, verbose_name='Name (Chinese)')),
                ('admission_hk', models.DateField(blank=True, null=True, verbose_name='Admission in Hong Kong')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('fax', models.CharField(blank=True, max_length=255)),
                ('lawsochk_profile', models.URLField(blank=True, null=True, verbose_name='hklawsoc.org.hk Profile URL')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LawyerPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=255)),
                ('post_zh', models.CharField(blank=True, max_length=255, verbose_name='Post (Chinese)')),
                ('from_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hourly_rate', models.PositiveIntegerField(default=0)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legitbase.LawFirm')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legitbase.Lawyer')),
            ],
        ),
        migrations.CreateModel(
            name='LawyerService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=0)),
                ('is_hourly_rate', models.BooleanField(choices=[((False, 'Fixed Fee'), (True, 'Hourly Rate'))], default=False)),
                ('lawyer_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legitbase.LawyerPost')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc_zh',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description (Chinese)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_zh',
            field=models.CharField(blank=True, max_length=80, verbose_name='Name (Chinese)'),
        ),
        migrations.AddField(
            model_name='lawyerservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legitbase.Category'),
        ),
        migrations.AddField(
            model_name='lawyerpost',
            name='services',
            field=models.ManyToManyField(through='legitbase.LawyerService', to='legitbase.Category'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='firms',
            field=models.ManyToManyField(through='legitbase.LawyerPost', to='legitbase.LawFirm'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='languages',
            field=models.ManyToManyField(to='legitbase.Language'),
        ),
    ]
