# Generated by Django 2.0.2 on 2018-02-26 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0002_auto_20180226_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LawyerJurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legitbase.Jurisdiction')),
            ],
        ),
        migrations.RenameField(
            model_name='lawyer',
            old_name='admission_hk',
            new_name='admission_date_hk',
        ),
        migrations.AlterField(
            model_name='lawyerservice',
            name='is_hourly_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lawyerjurisdiction',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legitbase.Lawyer'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='jurisdictions',
            field=models.ManyToManyField(through='legitbase.LawyerJurisdiction', to='legitbase.Jurisdiction'),
        ),
    ]
