# Generated by Django 2.0.2 on 2018-02-28 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0003_auto_20180226_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='HKDistrict',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_zh', models.CharField(max_length=255, verbose_name='Name (Chinese)')),
                ('region', models.CharField(choices=[('HK', 'Hong Kong'), ('KLN', 'Kowloon'), ('NT', 'New Territories')], max_length=3)),
            ],
            options={
                'verbose_name': 'HK District',
            },
        ),
        migrations.AddField(
            model_name='lawyerservice',
            name='free_consultation_minutes',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (15, 'Under 15 Minutes'), (30, '15-30 Minutes'), (1000000, '30 Minutes or more')], default=0),
        ),
        migrations.AlterField(
            model_name='lawyerservice',
            name='service',
            field=models.ForeignKey(limit_choices_to={'numchild': 0}, on_delete=django.db.models.deletion.CASCADE, to='legitbase.Category'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legitbase.HKDistrict'),
        ),
    ]
