# Generated by Django 2.0.2 on 2018-02-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0004_auto_20180228_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hkdistrict',
            options={'ordering': ['region', 'code'], 'verbose_name': 'HK District'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['glottocode']},
        ),
        migrations.AddField(
            model_name='language',
            name='glottocode',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Glottocode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='iso639_3',
            field=models.CharField(blank=True, max_length=3, verbose_name='ISO 639-3 Code'),
        ),
        migrations.RunSQL('DROP TABLE IF EXISTS "legitbase_lawyer_languages";'),
        migrations.RunSQL('CREATE TABLE "legitbase_lawyer_languages" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "lawyer_id" integer NOT NULL REFERENCES "legitbase_lawyer" ("id") DEFERRABLE INITIALLY DEFERRED, "language_id" varchar(8) NOT NULL REFERENCES "legitbase_language" ("glottocode") DEFERRABLE INITIALLY DEFERRED);'),
        migrations.RunSQL('CREATE UNIQUE INDEX legitbase_lawyer_languages_lawyer_id_language_id_cf563e9f_uniq ON "legitbase_lawyer_languages" ("lawyer_id", "language_id");'),
        migrations.RunSQL('CREATE INDEX "legitbase_lawyer_languages_lawyer_id_5d688b31" ON "legitbase_lawyer_languages" ("lawyer_id");'),
        migrations.RunSQL('CREATE INDEX "legitbase_lawyer_languages_language_id_15c65a09" ON "legitbase_lawyer_languages" ("language_id");'),
        migrations.AlterField(
            model_name='language',
            name='name_zh',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (Chinese)'),
        ),
    ]
