# Generated by Django 2.0.2 on 2018-02-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0005_auto_20180228_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='lawyer/photo/'),
        ),
    ]
