# Generated by Django 2.0.2 on 2018-02-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0004_cannotquote'),
        ('legitbase', '0006_lawyer_photo'),
    ]

    operations = [
    ]
