# Generated by Django 2.0.2 on 2018-03-15 03:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legitbase', '0009_auto_20180306_0340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawfirm',
            options={'permissions': (('admin_firm', 'Can only change own law firm'),)},
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='admins',
            field=models.ManyToManyField(related_name='lawfirm_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cannotquote',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='cannotquote',
            name='message_zh',
            field=models.TextField(verbose_name='Message (Chinese)'),
        ),
    ]
