# Generated by Django 2.0.2 on 2018-03-19 03:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0010_auto_20180315_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerservice',
            name='time_estimate_minutes_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='lawfirm_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
