# Generated by Django 2.0.2 on 2018-03-20 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0011_auto_20180319_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='hkdistrict',
            options={'ordering': ['region', 'code'], 'verbose_name': 'HK District', 'verbose_name_plural': 'HK Districts'},
        ),
        migrations.AlterModelOptions(
            name='jurisdiction',
            options={'verbose_name': 'Jurisdiction', 'verbose_name_plural': 'Jurisdictions'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['glottocode'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='lawfirm',
            options={'permissions': (('admin_firm', 'Law Firm Admin: Can only change own law firm'),), 'verbose_name': 'Law Firm', 'verbose_name_plural': 'Law Firms'},
        ),
        migrations.AlterModelOptions(
            name='lawyer',
            options={'verbose_name': 'Lawyer', 'verbose_name_plural': 'Lawyers'},
        ),
        migrations.AlterModelOptions(
            name='lawyerjurisdiction',
            options={'verbose_name': 'Lawyer Jurisdiction', 'verbose_name_plural': 'Lawyer Jurisdictions'},
        ),
        migrations.AlterModelOptions(
            name='lawyerpost',
            options={'verbose_name': 'Lawyer Post', 'verbose_name_plural': 'Lawyer Posts'},
        ),
        migrations.AlterModelOptions(
            name='lawyerservice',
            options={'verbose_name': 'Lawyer Service', 'verbose_name_plural': 'Lawyer Services'},
        ),
        migrations.AlterField(
            model_name='cannotquote',
            name='category',
            field=models.OneToOneField(limit_choices_to={'numchild': 0}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='legitbase.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='cannotquote',
            name='message',
            field=models.TextField(verbose_name='Message (English)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='hkdistrict',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='hkdistrict',
            name='region',
            field=models.CharField(choices=[('HK', 'Hong Kong'), ('KLN', 'Kowloon'), ('NT', 'New Territories')], max_length=3, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='jurisdiction',
            name='jurisdiction',
            field=models.CharField(max_length=255, verbose_name='Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='address',
            field=models.TextField(verbose_name='Address (English)'),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='lawfirm_admins', to=settings.AUTH_USER_MODEL, verbose_name='Law Firm Admins'),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legitbase.HKDistrict', verbose_name='HK District'),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='fax',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='status',
            field=models.CharField(choices=[('X', 'Invalid'), ('T', 'Free Trial'), (' ', 'Normal'), ('!', 'Not Paying')], default=' ', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='fax',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='firms',
            field=models.ManyToManyField(through='legitbase.LawyerPost', to='legitbase.LawFirm', verbose_name='Firms'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='jurisdictions',
            field=models.ManyToManyField(through='legitbase.LawyerJurisdiction', to='legitbase.Jurisdiction', verbose_name='Jurisdictions'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='languages',
            field=models.ManyToManyField(to='legitbase.Language', verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='lawyer/photo/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='lawyerjurisdiction',
            name='admission_date',
            field=models.DateField(verbose_name='Admission Date'),
        ),
        migrations.AlterField(
            model_name='lawyerjurisdiction',
            name='jurisdiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legitbase.Jurisdiction', verbose_name='Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='lawyerjurisdiction',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legitbase.Lawyer', verbose_name='Lawyer'),
        ),
        migrations.AlterField(
            model_name='lawyerpost',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='lawyerpost',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legitbase.LawFirm', verbose_name='Firm'),
        ),
        migrations.AlterField(
            model_name='lawyerpost',
            name='from_date',
            field=models.DateField(verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='lawyerpost',
            name='hourly_rate',
            field=models.PositiveIntegerField(default=0, verbose_name='Hourly Rate'),
        ),
        migrations.AlterField(
            model_name='lawyerpost',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legitbase.Lawyer', verbose_name='Lawyer'),
        ),
        migrations.AlterField(
            model_name='lawyerpost',
            name='post',
            field=models.CharField(max_length=255, verbose_name='Post (English)'),
        ),
        migrations.AlterField(
            model_name='lawyerservice',
            name='free_consultation_minutes',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (15, 'Under 15 Minutes'), (30, '15-30 Minutes'), (1000000, '30 Minutes or more')], default=0, verbose_name='Free Consultation Offer (minutes)'),
        ),
        migrations.AlterField(
            model_name='lawyerservice',
            name='is_hourly_rate',
            field=models.BooleanField(default=False, verbose_name='Hourly Rate?'),
        ),
        migrations.AlterField(
            model_name='lawyerservice',
            name='lawyer_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legitbase.LawyerPost', verbose_name='Lawyer Post'),
        ),
        migrations.AlterField(
            model_name='lawyerservice',
            name='rate',
            field=models.PositiveIntegerField(default=0, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='lawyerservice',
            name='service',
            field=models.ForeignKey(limit_choices_to={'numchild': 0}, on_delete=django.db.models.deletion.CASCADE, to='legitbase.Category', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='lawyerservice',
            name='time_estimate_minutes_max',
            field=models.PositiveIntegerField(default=0, verbose_name='Max Estimated Time (minutes)'),
        ),
    ]
