# Generated by Django 2.0.2 on 2018-03-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0012_auto_20180320_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawfirm',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Subscription Ends'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Subscription Starts'),
        ),
    ]
