# Generated by Django 2.0.2 on 2018-03-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0013_auto_20180320_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawfirm',
            name='subscription_nag_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lawyerpost',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date on which this position ends. Leave blank if position is current.', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='lawyerpost',
            name='from_date',
            field=models.DateField(help_text='Date from which this position begins.', verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='lawyerpost',
            name='hourly_rate',
            field=models.PositiveIntegerField(default=0, help_text='in HKD', verbose_name='Hourly Rate'),
        ),
    ]
