# Generated by Django 2.0.3 on 2018-03-22 10:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0014_auto_20180321_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requester_name', models.CharField(max_length=255, verbose_name='Name')),
                ('requester_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('requester_phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Brief summary of this consultation')),
                ('time_choice1', models.DateTimeField(blank=True, null=True, verbose_name='First choice')),
                ('time_choice2', models.DateTimeField(blank=True, null=True, verbose_name='Second choice')),
                ('time_choice3', models.DateTimeField(blank=True, null=True, verbose_name='Third choice')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requester_ip', models.GenericIPAddressField()),
                ('requester_user_agent', models.TextField()),
                ('requester_lang', models.CharField(max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('followup1_at', models.DateTimeField(blank=True, null=True)),
                ('followup1_did_reply', models.NullBooleanField()),
                ('followup2_at', models.DateTimeField(blank=True, null=True)),
                ('followup2_did_reply', models.NullBooleanField()),
                ('is_spam', models.BooleanField(default=False)),
                ('lawyer_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='legitbase.LawyerService')),
            ],
        ),
    ]
