# Generated by Django 2.0.3 on 2018-03-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0015_lawyerservicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerservicerequest',
            name='followup1_lawyer_did_reply',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='lawyerservicerequest',
            name='followup1_lawyer_replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawyerservicerequest',
            name='followup1_requester_replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawyerservicerequest',
            name='followup2_lawyer_did_reply',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='lawyerservicerequest',
            name='followup2_lawyer_replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawyerservicerequest',
            name='followup2_requester_replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
