# Generated by Django 2.0.3 on 2018-06-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0016_auto_20180326_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='intro',
            field=models.TextField(blank=True, verbose_name='Introduction (English)'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='intro_zh',
            field=models.TextField(blank=True, verbose_name='Introduction (Chinese)'),
        ),
    ]
