# Generated by Django 2.0.3 on 2018-06-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0017_auto_20180611_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc_zh',
            field=models.TextField(blank=True, verbose_name='Description (Chinese)'),
        ),
    ]
