# Generated by Django 2.0.3 on 2018-06-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0018_auto_20180611_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cannotquote',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='unquotable',
            field=models.BooleanField(default=False, verbose_name='Unquotable'),
        ),
        migrations.DeleteModel(
            name='CannotQuote',
        ),
    ]
