# Generated by Django 2.0.3 on 2018-08-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0020_experience_itemrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerpost',
            name='precedence',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Precedence to show in service list'),
        ),
    ]
