# Generated by Django 2.0.3 on 2018-08-28 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0023_optionalcontact_optionalmedia_optionalresume_optionalresumeentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Court Case Number')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('title_zh', models.CharField(blank=True, max_length=255, verbose_name='標題')),
                ('content_en', models.TextField(blank=True, verbose_name='Content')),
                ('content_zh', models.TextField(blank=True, verbose_name='內文')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_cases', to='legitbase.Lawyer')),
            ],
        ),
    ]
