# Generated by Django 2.0.3 on 2018-08-28 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0024_optionalcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalIntro',
            fields=[
                ('lawyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='optional_intro', serialize=False, to='legitbase.Lawyer')),
                ('text_en', models.TextField(blank=True, verbose_name='Introduction (English)')),
                ('text_zh', models.TextField(blank=True, verbose_name='律師介紹 (中文)')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='lawyer/optional/')),
                ('video', models.FileField(blank=True, null=True, upload_to='lawyer/optional/')),
            ],
        ),
    ]
