# Generated by Django 2.0.3 on 2018-09-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0027_auto_20180831_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionalintro',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='lawyer/optional/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='optionalintro',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lawyer/optional/', verbose_name='Video'),
        ),
    ]
