# Generated by Django 2.0.3 on 2018-09-09 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0029_requestendorsement_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawyerpanel',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='optionalcase',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='optionalcase',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lawyerpanel',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='requestendorsement',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
