# Generated by Django 2.0.3 on 2018-09-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0031_auto_20180909_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionalresumeentry',
            name='lawfirm',
        ),
        migrations.AddField(
            model_name='optionalresume',
            name='desc_zh',
            field=models.TextField(blank=True, verbose_name='敍述 (中文)'),
        ),
        migrations.AddField(
            model_name='optionalresumeentry',
            name='position_zh',
            field=models.CharField(blank=True, max_length=255, verbose_name='職位 (中文)'),
        ),
        migrations.AlterField(
            model_name='optionalresume',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),
    ]
