# Generated by Django 2.0.3 on 2018-09-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0032_auto_20180913_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionalresumeentry',
            name='end_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Year'),
        ),
    ]
