# Generated by Django 2.0.3 on 2018-09-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legitbase', '0033_auto_20180926_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='embed_map',
            field=models.TextField(blank=True, null=True, verbose_name='map'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='travel_en',
            field=models.TextField(blank=True, verbose_name='Travel (English)'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='travel_zh',
            field=models.TextField(blank=True, verbose_name='Travel (Chinese)'),
        ),
    ]
