# Generated by Django 2.0.3 on 2018-08-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=80, verbose_name='Name (English)')),
                ('name_zh', models.CharField(max_length=80, verbose_name='Name (Chinese)')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.TextField(verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='blog.Category', verbose_name='Categories'),
        ),
    ]
