# Generated by Django 2.0.3 on 2018-09-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_title',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Link Title'),
        ),
    ]
