# Generated by Django 2.0.2 on 2018-03-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=100, verbose_name='URL')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_zh', models.CharField(max_length=200, verbose_name='Title (Chinese)')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('content_zh', models.TextField(blank=True, verbose_name='Content (Chinese)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('url',),
            },
        ),
    ]
