# Generated by Django 2.0.2 on 2018-03-15 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicpage',
            options={'ordering': ('url',), 'verbose_name': 'basicpage', 'verbose_name_plural': 'basicpages'},
        ),
    ]
